{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler",
    "version": "99.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compiler-99.0.0.jar",
          "url": "compiler-99.0.0.jar",
          "size": 1122368,
          "sha512": "60bcab4cb596943e28ae0492a8e35814934ef58ca2c370069f8cd8760e1c6e7dc79e420597e0d711049e5b7b018700e4cd0b4c53f8a961e34fd563bcd1352ee1",
          "sha256": "7ca185204b22a98ad55d670c8d06f586b40c8839673bb19e3caa35b0025ed914",
          "sha1": "d3b90412c1b323e180f5a5b18d7b667088169530",
          "md5": "9cc5efc6c4fcd74786525c6cdeb114af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-99.0.0.jar",
          "url": "compiler-99.0.0.jar",
          "size": 1122368,
          "sha512": "60bcab4cb596943e28ae0492a8e35814934ef58ca2c370069f8cd8760e1c6e7dc79e420597e0d711049e5b7b018700e4cd0b4c53f8a961e34fd563bcd1352ee1",
          "sha256": "7ca185204b22a98ad55d670c8d06f586b40c8839673bb19e3caa35b0025ed914",
          "sha1": "d3b90412c1b323e180f5a5b18d7b667088169530",
          "md5": "9cc5efc6c4fcd74786525c6cdeb114af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-99.0.0-sources.jar",
          "url": "compiler-99.0.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}